name: Deploy Website

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Build Docusaurus website
        run: |
          yarn 
          yarn build
      - name: Deploy to GitHub Pages
        if: success() && github.event_name == 'push'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
